name: ant_todo_list
description: "ANT TodoList"

publish_to: 'none' 

version: '1.0.0'

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  path: ^1.9.0
  sqflite: ^2.3.3  
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  lottie: ^3.1.2
  url_launcher: ^6.2.6
  flutter_launcher_icons: ^0.13.1
  #default packages
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ANT_TODOLIST_Icons.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

#  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottiefiles/
