name: ant_todo_list
description: "ANT TodoList"

publish_to: "none"

version: "1.0.1"

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  path: ^1.9.0
  sqflite: ^2.3.3
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  lottie: ^3.1.2
  url_launcher: ^6.2.6
  flutter_launcher_icons: ^0.14.1
  date_picker_timeline: ^1.2.6
  flutter_dropdown_alert: ^1.0.7
  #default packages
  cupertino_icons: ^1.0.6
  flutter_swipe_button: ^2.1.3
  flutter_icon_snackbar: ^1.2.1
  draggable_home: ^1.0.5
  flutter_bounceable: ^1.1.0
  get: ^4.6.6
  table_calendar: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ANT_TODOLIST_Icons.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

#  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottiefiles/
    - assets/icons/ANT_TODOLIST_Icons.png

  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700
    - family: Romnea
      fonts:
        - asset: assets/Fonts/Romnea-Italic.ttf

    - family: Kantumruy Reg
      fonts:
        - asset: assets/Fonts/KantumruyPro-Regular.ttf
    - family: Kantumruy Bold
      fonts:
        - asset: assets/Fonts/KantumruyPro-Bold.ttf
    - family: Bobble
      fonts:
        - asset: assets/Fonts/Kh-Phanith-Bobble.ttf
    - family: Ocean
      fonts:
        - asset: assets/Fonts/Kh-Phanith-Ocean.ttf
    - family: AB
      fonts:
        - asset: assets/Fonts/Rosela.ttf
    - family: PV
      fonts:
        - asset: assets/Fonts/KantumruyPro-Regular.ttf
